# Use an official Node.js runtime as a parent image
FROM node:16 as build-stage

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Копируем все остальные файлы проекта в текущую рабочую директорию контейнера
COPY . .

#  Собираем приложение для production с указанием переменной окружения VUE_APP_API_URL
ENV NODE_ENV=production
# 'localhost' should be changed to the resolveable FQDN of a real host where nginx is deployed to be able to proxy requests to backend
ENV VUE_APP_API_URL=https://momo-store.devops-practicum.ru:8081
RUN npm run build

# Второй этап: настраиваем Nginx для обслуживания статического содержимого
FROM nginx:stable-alpine
ARG VERSION
WORKDIR /app

# Копируем собранное приложение из предыдущего этапа в рабочую директорию Nginx
COPY --from=build-stage /app/dist ./momo-store

# Copy the custom Nginx configuration file
COPY default.conf /etc/nginx/conf.d/default.conf

# Конфигурируем Nginx для обслуживания статического содержимого
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
